-- Purpose:
-- Compute account-level fraud risk scores and tiers from staged activity and rule hits.
-- Inputs typically include:
--   - Staged transactions (stg_transactions)
--   - Staged rule hits (stg_fraud_rule_hits)
--   - Reference dimensions (accounts, customers, merchants, devices)
--
-- Common scoring components:
--   - Total rule hits and severity-weighted hits (HIGH > MED)
--   - Recency of suspicious activity (last_hit_ts, last_txn_ts)
--   - Behavioral signals (e.g., international transaction rate)
--   - Decline frequency or other risk indicators
--
-- Output:
--   - account_risk_scores (risk_score, risk_tier, last_txn_ts, last_hit_ts, etc.)
--
-- In this portfolio project, scoring is prototyped in Google Sheets and exported as
-- data/curated/account_risk_scores.csv. This file documents the intended SQL approach.
