-- Purpose:
-- Produce reporting tables/queries that power the Fraud Operations Summary dashboard.
-- Typical outputs include:
--   - Executive KPIs (volume, declines, total rule hits, severity counts)
--   - Highest risk accounts (ranked by risk_score and tier)
--   - Rule effectiveness (total hits, high/med mix, high-rate)
--   - Activity over time (rule hits by monitoring window)
--   - Account-level and customer-level fraud activity rollups
--
-- In this portfolio project, reporting is assembled in Google Sheets as the
-- Fraud Operations Summary dashboard, with supporting screenshots exported to /screenshots.
-- This file documents what would normally be implemented as SQL views or reporting tables.
