-- Purpose:
-- Define rule evaluation outputs and severity classification logic.
-- This layer typically:
--   - Applies rule conditions against staged transactions/login activity
--   - Writes outputs to fraud_rule_hits (rule_code, rule_severity, hit_ts, evidence)
--   - Uses configurable parameters (thresholds, geo conditions, velocity windows)
--
-- In this portfolio project, rule outputs and severity (HIGH / MED) are produced
-- in Google Sheets and exported as fraud_rule_hits.csv.
-- This file documents how the same logic would be implemented in SQL.
